Neos:
  Fusion:
    defaultContext:
      AiClassification: 'NEOSidekick\MediaUiAssetAiLabeling\Eel\AiClassificationHelper'
  Neos:
    modules:
      management:
        submodules:
          mediaui:
            additionalResources:
              javaScripts:
                'NEOSidekick.MediaUiAssetAiLabeling': 'resource://NEOSidekick.MediaUiAssetAiLabeling/Public/MediaUi/ai-classification.js'
